"""message

Revision ID: 0c990760a53a
Revises: 5ad8fcd72abc
Create Date: 2024-07-01 21:04:52.963835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c990760a53a'
down_revision = '5ad8fcd72abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
